### ISSUE TITLE
Name of the app?

### ISSUE THREAD

**Issue by guettli** [k3b/AndroFotoFinder#12]
The app is called "a Foto Finder" in most places.

The about dialog still calls it "Andro Foto Finder".

It looks better if the app has only one name. At least in the user visible area.

**Comment by k3b** [comment]
hello guettli

you are right: the technical name of the app is "Andro Foto Finder" which was displayed as "a Foto Finder" until version 0.4.1. Since there is already a program and a company that sounds similare to "a Foto Finder" i will change the display name to "a Photo Manager". However i donot want to change the technical name because i donot want to change the url of the sourcecode/wiki/fdroid-registration. I will change the text in the about-box to reflect this

**Comment by k3b** [comment]
I have renamed the app-titles 

* from "a Foto Finder" to "a Photo Manager" 
* and from  "a Foto Map" to "a Photo Map" 

but the technical name "AndroFotoFinder" must remain 

* because it is part of internet-url of this site
* it is used by android/fdroid-update mechanism
