### ISSUE TITLE
fullscreen ?

### ISSUE THREAD

**Issue by MaxLanar** [k3b/AndroFotoFinder#17]
Hi,
It'd be nice to be able to watch images in true fullscreen (only the pic on the screen, no title, etc)...

**Comment by k3b** [comment]
Hello Max, Thanks for posting the feature request.

I have just looked at what android-s-gallery is doing: they are auto-hiding the caption-bar with the menu items after a few seconds. if you single tap on the photo the actionbar/title reappears.

I have to find out how this is programatically done.

On my side this ticket has a very low priority because 
* the app is currently working 
* on my tablet title/menue does not hurt me
* and i have outer things in the queue for this hobby project with higher priority.
